# Generated by Django 3.1 on 2020-10-04 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.SmallIntegerField(unique=True)),
                ('time_breakfast', models.CharField(blank=True, default='', max_length=50)),
                ('time_lunch', models.CharField(blank=True, default='', max_length=50)),
                ('time_dinner', models.CharField(blank=True, default='', max_length=50)),
                ('menus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant', to='food.menu')),
            ],
        ),
    ]
