# Generated by Django 3.1 on 2020-10-06 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_menu_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='is_vegetarian',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='without_fork',
        ),
        migrations.AddField(
            model_name='menu',
            name='is_vegetarian',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menu',
            name='without_fork',
            field=models.BooleanField(default=False),
        ),
    ]
