# Generated by Django 3.1 on 2020-10-06 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20201006_0357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='menus',
        ),
        migrations.AddField(
            model_name='menu',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='food.restaurant'),
        ),
    ]
