# Generated by Django 3.1 on 2020-10-10 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_auto_20201006_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='time',
            field=models.SmallIntegerField(choices=[(0, 'ALL'), (1, 'BREAKFAST'), (2, 'LUNCH'), (3, 'DINNER')], default=0),
        ),
        migrations.AlterField(
            model_name='menu',
            name='date',
            field=models.DateField(),
        ),
    ]
